name: pageloader

version: 3.3.1

description:
  Supports the creation of page objects that can be shared between in-browser tests
  and WebDriver tests.

homepage: https://github.com/google/pageloader

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  analyzer: '>=1.4.0 <=4.0.0'
  build: '>=1.1.0 <=3.0.0'
  built_value: '^8.0.0'
  build_config: '^1.0.0'
  matcher: '>=0.12.10'
  quiver: '^3.0.0'
  source_gen: '>=0.9.1 <=2.0.0'
  webdriver: '>=3.0.0'

dev_dependencies:
  build_runner: '^2.0.0'
  built_value_generator: '^8.0.0'
  path: '^1.8.0'
  test: '^1.16.0'
